project_id = "ptwytypavumcrbofspno"

[functions.public-config]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.social-write]
verify_jwt = false

[functions.sync-privy-user]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.launchpad-create]
verify_jwt = false

[functions.launchpad-swap]
verify_jwt = false

[functions.launchpad-claim-fees]
verify_jwt = false

[functions.launchpad-earnings]
verify_jwt = false

[functions.token-metadata]
verify_jwt = false
