project_id = "ptwytypavumcrbofspno"

[functions.public-config]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.social-write]
verify_jwt = false

[functions.sync-privy-user]
verify_jwt = false

[functions.update-profile]
verify_jwt = false
